server:
  port: 8888

spring:
  thymeleaf:
    prefix: classpath:/templates/
    cache: false
    suffix: .html
#  mvc:
#    static-path-pattern: /**
  profiles:
    active: stage
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/demo
      username: root
      password: root
      type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  redis:
      host: localhost
      port: 6379
      cache_name: XiChuanRedis

mybatis:
  type-aliases-package: com.example.demo.domain
  mapperLocations: com/example/demo/mapper/*Mapper.xml
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true

testName:
  applicationName: testRedis