server:
  port: 8888

#book.name : SpringCloud
#book.author : ZhaiYongChao
#desc : ${book.author} is writing 《${book.name}》

spring:
  thymeleaf:
    prefix: classpath:/templates/
    cache: false
    suffix: .html
  profiles:
    active: stage
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/demo
      username: root
      password: root
      type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

#spring:
#  mvc:
#    view:
#      prefix: /WEB-INF/view/
#      suffix: .html

mybatis:
  type-aliases-package: com.example.demo.domain
  mapperLocations: com/example/demo/mapper/*Mapper.xml
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true