server:
  port: 8080

#book.name : SpringCloud
#book.author : ZhaiYongChao
#desc : ${book.author} is writing 《${book.name}》

spring:
  thymeleaf:
    prefix: classpath:/templates/
    cache: false
  profiles:
    active: stage